name = "chandler-blog-v2"
account_id = ""  # Your Cloudflare account ID goes here
workers_dev = true
route = ""
zone_id = ""  # Your Cloudflare zone ID goes here
compatibility_date = "2023-10-30"

[site]
bucket = "_site"  # The directory where Eleventy outputs the built site

[build]
command = "npm run build"  # The command to build your site

[env.production]
workers_dev = false

[observability.logs]
enabled = true
